fix(build): missing the `caniuse-lite` package
Error:
- Error: Cannot find module 'caniuse-lite/data/features/css-unicode-bidi'

Solution:
- I ran into this issue while working on a Vue project and I fixed it by installing the `caniuse-lite` package again.
Just run `npm i caniuse-lite in your terminal.
https://stackoverflow.com/a/66150844