BUGFIX. Unable to update sass-loader from 7.3.1 to 12.6.0
Error:
- TypeError: this.getOptions is not a function
https://stackoverflow.com/a/66087132

Solution:
- The sass-loader@11.0.0 does not seem to work with vue@2.6.12. The version 11 does not work with Vue because v11 requires Webpack v5. Use the version 10 instead